# require "prawn"

class MandateUser
  attr_accessor :user

  def initialize(user)
    @user = user
  end

  def generate
    html = %{
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:8.05pt;"><span style="font-size:21pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">ABRECHNUNGSMANDAT</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Dieses Abrechnungsmandat wird abgeschlossen zwischen:</span></p>

      <ul>
        <li>
          <span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">der Gesellschaft bridlx gemeldet am Amtsgericht Bayreuth (HRB 7355)</span><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:#ffffff;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">deren Gesch&auml;ftssitz sich in: Albert-Ruckdeschel-Str. 9, 95326 Kulmbach befindet.</span>
        </li>
      </ul>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">und</span></p>
      <ul>
          <li aria-level="1">
              <span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">dem Einzelunternehmer #{user.first_name}, #{user.last_name}&nbsp;</span>
          </li>
      </ul>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:9.95pt;"><span style="font-size:18pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Vorwort</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Um eine vereinfachte und automatisierte Rechnungsstellung bez&uuml;glich der erbrachten Leistungen zwischen Einzelunternehmer sowie Auftraggebern sicherzustellen, h&auml;lt sich die Gesellschaft vor, die Rechnungen im Namen der Einzelunternehmer sowohl zu erstellen als auch auszustellen.</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Demnach treffen die bridlx GmbH und der Einzelunternehmer eine Vereinbarung &uuml;ber jegliches Forderungsmanagements des Einzelunternehmers bez&uuml;glich der erbrachten Leistungen.</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:9.95pt;"><span style="font-size:18pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1 &ndash; Auftragsgegenstand</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Der Einzelunternehmer beauftragt die Gesellschaft in seinem Namen und in seinem Auftrag alle Original-, Abschlags- und Korrekturrechnungen bez&uuml;glicher der erbrachten &amp; bestellten Leistungen zu generieren.</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:9.95pt;"><span style="font-size:18pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">2 &ndash; Auftragsdauer</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Der Auftrag wird am Tag der Annahme durch den Einzelunternehmer wirksam und gilt als abgeschlossen, sofern die beauftragte Leistung im vollen Ma&szlig;e oder nach Erbringung von Teilpaketen (Probetermin) durchgef&uuml;hrt wurde.</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">W&auml;hrend der gesamten Dauer des Auftrags wird der Einzelunternehmer keine anderen Dienstleister mit der Rechnungsstellung bez&uuml;glich der Leistungen aus einem mit einem Auftraggeber &uuml;ber die Plattform abgeschlossenen Vertrag beauftragen.</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:9.95pt;"><span style="font-size:18pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">3 &ndash; Verg&uuml;tung</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Gem&auml;&szlig; der allgemeinen Gesch&auml;ftsbedingungen ist die Verg&uuml;tung f&uuml;r das gesamthafte Forderungsmanagement in der von dem Einzelunternehmer an die Gesellschaft zu zahlenden Provision enthalten.</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:9.95pt;"><span style="font-size:18pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">4 &ndash; Pflichten der bridlx GmbH</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Der Gesellschaft verpflichtet sich, die Rechnungen im Namen und im Auftrag des Einzelunternehmers auf Grundlage der von ihm gegebenen Informationen zu erstellen.</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Nachdem der best&auml;tigten Auftragsannahme durch den Einzelunternehmer werden die Rechnungen auf elektronischem Wege dem Auftragsgeber verteilt.&nbsp;</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Die Gesellschaft wird daf&uuml;r sorgen, dass die Rechnungen den Vermerk &quot;Rechnung erstellt durch [Name der Gesellschaft] im Namen und f&uuml;r Rechnung von [Name / Bezeichnung des Einzelunternehmers], Steuernummer: [Steuernummer des Einzelunternehmers]&quot; tragen.</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Im Falle eines Antrags auf Korrektur der Rechnung seitens des Einzelunternehmers verpflichtet sich die Gesellschaft, unverz&uuml;glich eine Korrekturrechnung auszustellen, sofern ein begr&uuml;ndeter Anspruch auf Korrektur besteht.</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Die Gesellschaft verpflichtet sich hinsichtlich des Forderungsmanagements, f&uuml;r die Rechnungsnummer der jeweiligen Rechnungen, eine f&uuml;r jeden Einzelunternehmer unterscheidbare chronologische und fortlaufende ID zu verwenden.</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:9.95pt;"><span style="font-size:18pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">5- Pflichten des Einzelunternehmers</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">F&uuml;r die Einhaltung der gesetzlichen und steuerlichen Pflichten hinsichtlich der Rechnungsstellung aus Original-, Abschlags-und / oder Korrekturrechnungen, die in seinem Namen und in seinem Auftrag durch die Gesellschaft ausgestellt wurden, hat der Einzelunternehmer selbst zu sorgen.&nbsp;</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Folglich ist die Notwendigkeit zur Registrierung bei den Finanzbeh&ouml;rden sowie die Notwendigkeit zur Anmeldung und Abf&uuml;hrung der Umsatzsteuer (abh&auml;ngig von Rechtsform) unumg&auml;nglich.</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Insbesondere ist der Einzelunternehmer allein verantwortlich f&uuml;r die Bestimmung des f&uuml;r die Rechnungsstellung anwendbaren Rechts sowie f&uuml;r die &Uuml;bermittlung der erforderlichen Informationen an die Gesellschaft, damit diese die Rechnungen erstellen kann, die den geltenden Vorschriften entsprechen. Die Vorschriften diesbez&uuml;glich sind von der landes&uuml;blichen Gesetzgebung abh&auml;ngig.</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Der Einzelunternehmer verpflichtet sich weiterhin die f&auml;llige Umsatzsteuer zu begleichen, wenn diese zu Unrecht ausgewiesen wird.</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Daher verpflichtet sich der Einzelunternehmer ausdr&uuml;cklich:</span></p>
      <ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
          <li>
              <p style="line-height:1.2;margin-top:14pt;margin-bottom:0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">die Gesellschaft die vollst&auml;ndige Liste der Informationen zu &uuml;bermitteln, die in den Rechnungen nach dem f&uuml;r die Rechnungsstellung des Einzelunternehmers anwendbaren Rechts aufgef&uuml;hrt sein m&uuml;ssen,</span></p>
          </li>
          <li>
              <p style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">die Begleichung der Steuerlast, welche den im Namen und Auftrag erstellten Rechnungen zu Grunde liegt</span></p>
          </li>
          <li>
              <p style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">unverz&uuml;glich den Rechnungsdurschlag zu fordern, wenn er ihm nicht innerhalb der angegebenen Fristen und zu den hier genannten Bedingungen durch die Gesellschaft zur Verf&uuml;gung gestellt wurde;</span></p>
          </li>
          <li>
              <p style="line-height:1.2;margin-top:0pt;margin-bottom:14pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">jegliche &Auml;nderung der Pflichtangaben zur Identifizierung seines Unternehmens anzuzeigen.</span></p>
          </li>
      </ul>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Der Einzelunternehmer hat eine Frist von 3 Tagen, um die Informationen, die in der in seinem Namen und in seinem Auftrag ausgestellten Rechnung enthalten sind, zu bestreiten und die Forderung nach einer Korrektur an die Gesellschaft heranzutragen. Sofern innerhalb der Frist keine Einw&auml;nde an die Gesellschaft vorgebracht werden, gilt sie als vom Einzelunternehmer angenommen.</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:9.95pt;"><span style="font-size:18pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Artikel VII- &Auml;nderungen</span></p>
      <p style="line-height:1.2;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10.5pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Jeder Nachtrag eines Auftrags muss in derselben Form von allen Personen vorgenommen werden, die von den Parteien zu diesem Zweck ordnungsgem&auml;&szlig; erm&auml;chtigt sind.</span></p>
      <p><br></p>
      <p><br></p>
    }
    kit = PDFKit.new(html, :page_size => 'Letter')
    pdf = kit.to_pdf

    # kit.to_file('./mandate.pdf')

    # Prawn::Document.generate("hello.pdf") do
    #   text "Hello World!"
    # end
  end
end
